# Generated by Django 4.1 on 2022-08-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_action_created_at_alter_session_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.account'),
        ),
    ]
